# Generated by Django 3.2.9 on 2021-11-28 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codeInOne_API', '0002_auto_20211128_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
