# Generated by Django 3.2.9 on 2021-11-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeInOne_API', '0003_alter_challenge_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='release_date',
        ),
    ]
