# Generated by Django 3.2.9 on 2021-11-28 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codeInOne_API', '0005_alter_challenge_challengedesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
